#!/usr/bin/env python
#-*- coding:utf-8 -*-

#  Copyright (C) 2010-2018  CEA/DEN
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2.1 of the License.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA

'''This file is the main entry file to use salomeTools
'''

import os
import sys

# get path to salomeTools sources
satdir  = os.path.dirname(os.path.realpath(__file__))

# Make the src & commands package accessible from all code
sys.path.insert(0, satdir)


#################################
# MAIN
#################################
if __name__ == "__main__":
    import src
    from src.salomeTools import Sat
    import src.debug as DBG # Easy print stderr (for DEBUG only)

    _debug = False          # Have to be False in production (for DEBUG only)
    DBG.push_debug(_debug)

    # instantiate the salomeTools class with correct options
    sat = Sat(sys.argv[1:])
    # or sat = Sat("config -l") for example
    returnCode = sat.execute_command()
    DBG.write("sat exit code", returnCode)

    sys.exit(returnCode.toSys())
        
